import random

fragenarten = [
    "Nenne", "Zähle auf", "Gib an", "Beschreibe", "Erkläre",
    "Führe auf", "Was sind", "Liste"
]
themen = [
    "Vorteile von KI", "Nachteile von Cloud-Computing", "Beispiele für Transfer Learning",
    "Risiken von KI-Systemen", "ethische Herausforderungen bei Machine Learning",
    "gängige ML-Algorithmen", "Frameworks für Deep Learning", "Probleme bei Big Data",
    "Anwendungsgebiete für Natural Language Processing", "Schritte im Data-Science-Prozess",
    "Möglichkeiten zur Datenbereinigung", "Kriterien für ein gutes Trainingsset",
    "Metriken zur Bewertung von ML-Modellen", "Arten neuronaler Netze",
    "Anwendungsfelder von Computer Vision", "Voraussetzungen für erfolgreiches Model-Deployment",
    "Regularisierungstechniken in ML", "Cloud-Anbieter für AIaaS", "Konzepte des Transfer Learning",
    "Herausforderungen bei Explainable AI", "Cloud-Services mit GPU-Unterstützung",
    "Konzepte der Datenanonymisierung", "Strategien zur Fehlerbehandlung in KI-Systemen",
    "Arten von Datensätzen im ML", "Aktuelle Forschungstrends in KI",
    "Best Practices für Feature Engineering", "Schwachstellen von Chatbots",
    "Bedeutung von Trainingsdatenmenge", "Limits von generativer KI",
    "Sicherheitsaspekte beim Model Deployment", "Einsatzmöglichkeiten von KI in der Produktion",
    "KI-Anwendungen in der Medizin", "Tipps für Data Labeling", "Open-Source-Tools für KI",
    "Vorteile von multimodaler KI", "ML in der Bildverarbeitung", "Einsatz von KI für Nachhaltigkeit",
    "Schnittstellen zwischen Mensch und KI", "Zukunftsperspektiven von AIaaS",
    "Automatisierung durch KI", "KI im Bildungswesen", "Einsatz von KI in der Sprachverarbeitung",
    "Künstliche Intelligenz in der Industrie 4.0", "Bedeutung von Vortrainierten Modellen",
    "Sinn und Unsinn von KI-Ethik-Richtlinien", "KI in der Finanzbranche",
    "Rolle von KI im Umweltschutz", "KI und Datenschutz", "Transferierbarkeit von ML-Modellen",
    "Vorteile und Grenzen von AutoML", "KI in kleinen und mittleren Unternehmen",
    "Verantwortungsvoller KI-Einsatz"
]

# Deine bestehenden Prompts
base_prompts = [
    "Was versteht man unter AI as a Service?",
    "Nenne die Hauptvorteile von Machine Learning in der Cloud.",
    "Welche Herausforderungen gibt es bei KI-Ethik?",
    "Wie funktioniert supervised learning?",
    "Was ist der Unterschied zwischen klassischem Programmieren und ML?",
    "Wofür wird Reinforcement Learning eingesetzt?",
    "Was ist ein neuronales Netz?",
    "Erkläre Overfitting mit einem Beispiel.",
    "Wie kann man Daten für ML-Anwendungen vorverarbeiten?",
    "Welche Bedeutung haben GPUs für KI?",
    "Was ist Transfer Learning?",
    "Nenne bekannte Anbieter von AIaaS.",
    "Wie lässt sich KI für die Automatisierung nutzen?",
    "Was sind Biases in ML-Modellen?",
    "Was ist ein Hyperparameter in ML?",
    "Wie funktioniert Feature Engineering?",
    "Was ist die Rolle von APIs im Kontext von AIaaS?",
    "Wie wird Natural Language Processing in der Industrie eingesetzt?",
    "Welche Programmiersprachen sind am wichtigsten für KI?",
    "Erkläre den Begriff Big Data.",
    "Was sind die Risiken von generativer KI?",
    "Wie kann man ML-Modelle überwachen?",
    "Was ist Explainable AI (XAI)?",
    "Wie funktioniert ein Decision Tree?",
    "Erkläre Data Augmentation.",
    "Welche Cloud-Plattformen bieten KI-Dienste?",
    "Wie kann man Deep Learning effizient trainieren?",
    "Was sind Use Cases für KI im Gesundheitswesen?",
    "Wie funktioniert ein Recommendation System?",
    "Was ist unsupervised learning?",
    "Was ist ein Random Forest?",
    "Wie erkennt man Anomalien mit ML?",
    "Welche Rolle spielt Data Privacy bei AIaaS?",
    "Wie funktioniert der Turing-Test?",
    "Erkläre Computer Vision.",
    "Wie kann man Modelle gegen Angriffe absichern?",
    "Was ist ein Pretrained Model?",
    "Wie funktioniert Federated Learning?",
    "Was ist die Rolle von Open Source in KI?",
    "Wie werden ML-Modelle in Produktion gebracht?",
    "Was ist der Unterschied zwischen KI und ML?",
    "Wie kann KI nachhaltiger werden?",
    "Wie funktioniert sentiment analysis?",
    "Wie werden Chatbots trainiert?",
    "Welche Herausforderungen gibt es bei der Datenqualität?",
    "Wie kann man Bias im Training reduzieren?",
    "Was sind die Trends im Bereich AIaaS?",
    "Wie kann man ML-Projekte agil umsetzen?",
    "Was ist ein Datensatz?",
    "Wie wichtig ist Datenqualität für KI-Systeme?",
    "Was ist der Unterschied zwischen künstlicher Intelligenz und schwacher KI?",
    "Wie kann Explainable AI zur Akzeptanz von KI beitragen?",
    "Welche regulatorischen Anforderungen gelten für KI-Systeme in Europa?",
    "Was sind Edge AI und ihre Vorteile?",
    "Wie können Unternehmen von AIaaS profitieren?",
    "Welche ethischen Leitlinien sollten bei KI-Projekten beachtet werden?",
    "Wie wird die Qualität von Trainingsdaten gemessen?",
    "Was sind typische Fehlerquellen bei ML-Projekten?",
    "Wie erfolgt die Evaluation von KI-Modellen?",
    "Was ist eine Konfusionsmatrix?",
    "Wie kann Cloud Computing die Entwicklung von KI beschleunigen?",
    "Wie sieht die Zukunft von AIaaS aus?",
    "Was versteht man unter Model Deployment?",
    "Wie lassen sich KI-Modelle skalieren?",
    "Wie kann man Overfitting verhindern?",
    "Welche Tools gibt es für das Monitoring von ML-Modellen?",
    "Wie wird Datenanonymisierung im ML-Kontext umgesetzt?",
    "Was sind typische Herausforderungen bei der Integration von KI in bestehende Systeme?",
    "Wie kann man Datensätze für ML synthetisch erzeugen?",
    "Wie können Unternehmen KI verantwortungsvoll einsetzen?",
    "Was ist Transfer Learning und wann ist es sinnvoll?",
    "Welche Rolle spielen Datenpipelines in ML-Projekten?",
    "Wie kann man Modelle für verschiedene Sprachen trainieren?",
    "Wie wirkt sich die Größe eines Modells auf dessen Energieverbrauch aus?",
    "Was sind aktuelle Trends in der Forschung zu generativer KI?",
    "Wie kann Bias in Datensätzen erkannt werden?",
    "Wie läuft ein typischer AIaaS-Prozess ab?",
    "Was sind die wichtigsten Anforderungen an Datensicherheit bei AIaaS?",
    "Wie wird Explainable AI in der Praxis angewendet?",
    "Was bedeutet Zero-Shot Learning?",
    "Welche Rolle spielt Transfer Learning im KI-Bereich?",
    "Wie können KI-Modelle in Echtzeit eingesetzt werden?",
    "Was sind die Vorteile von AutoML?",
    "Wie wird Fairness in KI-Systemen sichergestellt?",
    "Welche KI-Technologien werden in der Industrie am meisten genutzt?",
    "Was sind die Aufgaben eines Data Scientists?",
    "Welche Unterschiede gibt es zwischen Regression und Klassifikation?",
    "Wie funktioniert Clustering?",
    "Was ist ein Embedding im ML-Kontext?",
    "Welche Bedeutung hat Feature Selection?",
    "Wie kann man die Performanz von ML-Modellen steigern?",
    "Was ist Reinforcement Learning und wofür wird es genutzt?",
    "Wie kann man Daten für das Training augmentieren?",
    "Was ist eine ROC-Kurve?",
    "Wie funktioniert k-Nearest Neighbors?",
    "Wie werden Modelle mit Transfer Learning weiterentwickelt?",
    "Was sind GANs (Generative Adversarial Networks)?",
    "Wie lässt sich die Modellgüte bewerten?",
    "Welche Bedeutung haben Labels im Machine Learning?",
    "Wie funktioniert Cross-Validation?",
    "Was ist eine Epoch im Training eines ML-Modells?",
    "Wie kann man Modelle interpretierbar machen?",
    "Was sind die wichtigsten Anwendungsfälle für ML in der Industrie?",
    "Wie kann man Daten für maschinelles Lernen anonymisieren?",
    "Was versteht man unter Batch Learning?",
    "Was ist Semi-Supervised Learning?",
    "Wie können Ausreißer im Datensatz erkannt und behandelt werden?",
    "Was sind Herausforderungen bei Multi-Label-Klassifikation?",
]

while len(base_prompts) < 500:
    fr = random.choice(fragenarten)
    th = random.choice(themen)
    prompt = f'{fr} {th}.'
    if prompt not in base_prompts:
        base_prompts.append(prompt)

# Speichern als Klartext, eine Zeile pro Prompt
with open("base_prompts.txt", "w", encoding="utf-8") as f:
    for p in base_prompts:
        f.write(p + "\n")

print("Fertig! Datei 'base_prompts.txt' erstellt.")
